[paths]
data_input_file = data/raw/my_data.csv
results_output_dir = results/
train_path_h5 = /home/students/wcao/eeg_train_seizure_h5
tmp_path = /tmp
segments_json = data/raw/segments.json

[data_loader]
load_by_segment = False
load_by_patient = True
# 48 segments
# patients = aaaaardk

# 2 segments, 3000 data points in total
# patients = aaaaafxr
patients = hahaha
# patients = aaaaahof
segments = aaaaafxr_s002_t005

# longest length
# segments = aaaaasdq_s002_t004 
# segments = aaaaajrs_s001_t001 # median length

# shortest length
# segments = aaaaappt_s004_t001 


[logging]
log_file = /tmp/pipeline.log
log_level = INFO

[pipeline_modules]
run_cwt = True
run_bispectrum = True
run_visualization = False
run_stat = True
max_workers = 1
run_aggregate_stat = True
run_aggregate_visualization = True
run_aggregate_network_analysis = True
run_network_analysis = True

[run_bispectrum_params]
bispectrum_smoothed = False

[run_stat_params]
save_path = results/stats/

[run_visualization_params]
# property_names = biamplitude, bicoherence
property_names = biamplitude
smooth_per_sec = True
save_path = results/visualizations/instant
all_channel = True
single_channel = True

[run_aggregate_stat_params]
aggregate_segment_results = False
aggregate_segment_stats = True

[run_aggregate_visualization_params]
aggregated_stats_file_path = results/stats/global/