[paths]
data_input_file = data/raw/my_data.csv
results_output_dir = results/
train_path_h5 = /home/students/wcao/eeg_train_seizure_h5
tmp_path = /tmp
segments_json = data/raw/segments.json

[data_loader]
load_by_segment = True
load_by_patient = False
patients = aaaaardk
# longest length
segments = aaaaasdq_s002_t004 
# segments = aaaaajrs_s001_t001 # median length

# shortest length
# segments = aaaaappt_s004_t001 


[logging]
log_file = logs/long.log
log_level = INFO

[pipeline_modules]
run_cwt = True
run_bispectrum = True
run_module_3 = False
max_workers = 1

[module_1_params]
some_parameter = 10.5